SELECT distinct ?regencyLabel (COUNT(?district) AS ?count) WHERE {

	{ ?district wdt:P31 wd:Q4200298 }
  	UNION { ?district wdt:P31 wd:Q3700011 }
	?district wdt:P2588 ?kemendagri .
	?district wdt:P131 ?regency .
	?district wdt:P2588 ?kemendagri .
	{ ?regency wdt:P31 wd:Q3191695 }
	UNION { ?regency wdt:P31 wd:Q3199141 }
	UNION { ?regency wdt:P31 wd:Q4272761 }
	UNION { ?regency wdt:P31 wd:Q11127777 }
	OPTIONAL { ?regency p:P31 [pq:P582 ?end ]. }
	FILTER(!BOUND(?end)) .
	?regency wdt:P131 wd:Q3630 .
	
	
	SERVICE wikibase:label {
	 bd:serviceParam wikibase:language "id" .
	}
}
GROUP BY ?regencyLabel
