SELECT distinct ?regency ?regencyLabel ?kemendagri WHERE {
			
	{ ?regency wdt:P31 wd:Q3191695 }
	UNION { ?regency wdt:P31 wd:Q3199141 }
	UNION { ?regency wdt:P31 wd:Q4272761 }
	UNION { ?regency wdt:P31 wd:Q11127777 }
	?regency wdt:P131 ?province .
	?regency wdt:P2588 ?kemendagri
	OPTIONAL { ?regency p:P31 [pq:P582 ?end ]. }
	FILTER(!BOUND(?end)) .
	
	?province wdt:P31 wd:Q5098 .
	
	SERVICE wikibase:label {
	 bd:serviceParam wikibase:language "id" .
	}
}
ORDER BY ?kemendagri
